"use client";

import { todoStore } from "@/store/todoStore";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<Provider store={todoStore}>
			<html lang="en">
				<body className={inter.className}>{children}</body>
			</html>
		</Provider>
	);
}
